Added simple script to create empty notebook

diff --git a/dot_local/bin/executable_mknb b/dot_local/bin/executable_mknb
--- a/dot_local/bin/executable_mknb
+++ b/dot_local/bin/executable_mknb
@@ -1,4 +1,11 @@
 #!/bin/bash
 
+if ! command -v jupytext &> /dev/null
+then
+    echo "jupytext command not found. Make sure it's available in PATH."
+    exit 1
+fi
+
+
 touch "$1".py
 jupytext --to notebook "$1".py
